### ISSUE TITLE
Language detection is not stable

### ISSUE THREAD

**Issue by Downchuck** [Mimino666/langdetect#8] opened 2015-05-29 21:12 UTC
Just testing the same input over and over, I get unstable results.
detect_langs shows why... same input (short text):

```
[en:0.612264348398, fr:0.387735651602]
[fr:0.571429613661, en:0.428570386339]
[fr:0.571428142838, en:0.428571857162]
[fr:0.507299170755, en:0.492700828387]
[en:0.570130701075, fr:0.429869298925]
[fr:0.714282326789, en:0.285717673211]
```

**Comment by Mimino666** [comment] 2015-05-29 23:21
Duplicate of issue #3.

**Closed** 2015-05-29 23:21 UTC
Labels: duplicate
